name: IIX.IO
author: DOPM
description: "Try and look nice site."
baseurl: "http://iix.io"
permalink: "/:dirname/:filename"
timezone: Asia/Jakarta

paginate: 10
paginate_path: "page/:num"

excludes: ["Makefile", "_config.yml"]

links:
  - name: About
    url: /resume
  - name: Chinese
    url: /zh/
  - name: English
    url: /en/

social:
  - name: Email
    url: "mailto:github@iwan.ca"
  - name: Twitter
    url: "https://twitter.com/iixio"
  - name: GitHub
    url: "https://github.com/iixio"


